#define MAX_DATA 10
#define MAX 255 
#define TAM_DISCIPLINA 255
#define TAM_PESSOA 255
#define MAX_ALUNO 100

#define MAX_CPF 13

#define MATRICULA_INVALIDA -1
#define SEXO_INVALIDO -2
#define CPF_INVALIDO -3
#define DATA_INVALIDA -4
#define LISTA_VAZIA -5
#define EXCLUSAO_SUCESSO -6
#define TA_CHEIO_PAIZAO -7
#define CODIGO_INVALIDO -8
#define SEMESTRE_INVALIDO -9
#define PROFESSOR_INVALIDO -10
#define NOME_INVALIDO -11
#define MATRICULA_REALIZADA -12
#define ALUNO_DESINSERIDO -13

